export interface GiteaRestOperation {
  operationId: string;
  method: "GET" | "POST" | "PUT" | "PATCH" | "DELETE" | "HEAD";
  path: string;
  tags: string[];
  parameterNames: string[];
}

function uniqueSorted(values: string[]): string[] {
  return [...new Set(values)].sort((a, b) => a.localeCompare(b));
}

function op(
  operationId: string,
  method: GiteaRestOperation["method"],
  path: string,
  tags: string[],
  parameterNames: string[]
): GiteaRestOperation {
  return { operationId, method, path, tags: uniqueSorted(tags), parameterNames: uniqueSorted(parameterNames) };
}

const OPERATIONS: GiteaRestOperation[] = [
  // ── Issues ───────────────────────────────────────────────────────────────────
  op("issueListIssues", "GET", "/repos/{owner}/{repo}/issues", ["issue"], ["owner", "repo", "state", "type", "labels", "milestone", "created_by", "assigned_by", "mentioned_by", "since", "before", "page", "limit"]),
  op("issueCreateIssue", "POST", "/repos/{owner}/{repo}/issues", ["issue"], ["owner", "repo"]),
  op("issueGetIssue", "GET", "/repos/{owner}/{repo}/issues/{index}", ["issue"], ["owner", "repo", "index"]),
  op("issueEditIssue", "PATCH", "/repos/{owner}/{repo}/issues/{index}", ["issue"], ["owner", "repo", "index"]),
  op("issueDeleteIssue", "DELETE", "/repos/{owner}/{repo}/issues/{index}", ["issue"], ["owner", "repo", "index"]),
  op("issueGetComments", "GET", "/repos/{owner}/{repo}/issues/{index}/comments", ["issue"], ["owner", "repo", "index", "since", "before", "page", "limit"]),
  op("issueCreateComment", "POST", "/repos/{owner}/{repo}/issues/{index}/comments", ["issue"], ["owner", "repo", "index"]),
  op("issueGetComment", "GET", "/repos/{owner}/{repo}/issues/comments/{id}", ["issue"], ["owner", "repo", "id"]),
  op("issueDeleteComment", "DELETE", "/repos/{owner}/{repo}/issues/comments/{id}", ["issue"], ["owner", "repo", "id"]),
  op("issueEditComment", "PATCH", "/repos/{owner}/{repo}/issues/comments/{id}", ["issue"], ["owner", "repo", "id"]),
  op("issueGetLabels", "GET", "/repos/{owner}/{repo}/issues/{index}/labels", ["issue"], ["owner", "repo", "index"]),
  op("issueAddLabel", "POST", "/repos/{owner}/{repo}/issues/{index}/labels", ["issue"], ["owner", "repo", "index"]),
  op("issueRemoveLabel", "DELETE", "/repos/{owner}/{repo}/issues/{index}/labels/{id}", ["issue"], ["owner", "repo", "index", "id"]),
  op("issueReplaceLabels", "PUT", "/repos/{owner}/{repo}/issues/{index}/labels", ["issue"], ["owner", "repo", "index"]),
  op("issueClearLabels", "DELETE", "/repos/{owner}/{repo}/issues/{index}/labels", ["issue"], ["owner", "repo", "index"]),
  op("issueGetMilestone", "GET", "/repos/{owner}/{repo}/milestones/{id}", ["issue"], ["owner", "repo", "id"]),
  op("issueGetMilestoneList", "GET", "/repos/{owner}/{repo}/milestones", ["issue"], ["owner", "repo", "state", "name", "page", "limit"]),
  op("issueCreateMilestone", "POST", "/repos/{owner}/{repo}/milestones", ["issue"], ["owner", "repo"]),
  op("issueEditMilestone", "PATCH", "/repos/{owner}/{repo}/milestones/{id}", ["issue"], ["owner", "repo", "id"]),
  op("issueDeleteMilestone", "DELETE", "/repos/{owner}/{repo}/milestones/{id}", ["issue"], ["owner", "repo", "id"]),
  op("issueListRepoIssueComments", "GET", "/repos/{owner}/{repo}/issues/comments", ["issue"], ["owner", "repo", "since", "before", "page", "limit"]),
  op("issueTrackedTimes", "GET", "/repos/{owner}/{repo}/issues/{index}/times", ["issue"], ["owner", "repo", "index", "user", "since", "before", "page", "limit"]),
  op("issueAddTime", "POST", "/repos/{owner}/{repo}/issues/{index}/times", ["issue"], ["owner", "repo", "index"]),
  op("issueDeleteTime", "DELETE", "/repos/{owner}/{repo}/issues/{index}/times/{id}", ["issue"], ["owner", "repo", "index", "id"]),

  // ── Repositories ─────────────────────────────────────────────────────────────
  op("repoGet", "GET", "/repos/{owner}/{repo}", ["repository"], ["owner", "repo"]),
  op("repoDelete", "DELETE", "/repos/{owner}/{repo}", ["repository"], ["owner", "repo"]),
  op("repoEdit", "PATCH", "/repos/{owner}/{repo}", ["repository"], ["owner", "repo"]),
  op("repoCreate", "POST", "/user/repos", ["repository"], []),
  op("repoCreateOrgRepo", "POST", "/orgs/{org}/repos", ["repository"], ["org"]),
  op("repoSearch", "GET", "/repos/search", ["repository"], ["q", "topic", "includeDesc", "uid", "priority_owner_id", "team_id", "starredBy", "private", "is_private", "template", "archived", "mode", "exclusive", "sort", "order", "page", "limit"]),
  op("repoGetContents", "GET", "/repos/{owner}/{repo}/contents/{filepath}", ["repository"], ["owner", "repo", "filepath", "ref"]),
  op("repoCreateFile", "POST", "/repos/{owner}/{repo}/contents/{filepath}", ["repository"], ["owner", "repo", "filepath"]),
  op("repoUpdateFile", "PUT", "/repos/{owner}/{repo}/contents/{filepath}", ["repository"], ["owner", "repo", "filepath"]),
  op("repoDeleteFile", "DELETE", "/repos/{owner}/{repo}/contents/{filepath}", ["repository"], ["owner", "repo", "filepath"]),
  op("repoGetEditorConfig", "GET", "/repos/{owner}/{repo}/editorconfig/{filepath}", ["repository"], ["owner", "repo", "filepath", "ref"]),
  op("repoListBranches", "GET", "/repos/{owner}/{repo}/branches", ["repository"], ["owner", "repo", "page", "limit"]),
  op("repoGetBranch", "GET", "/repos/{owner}/{repo}/branches/{branch}", ["repository"], ["owner", "repo", "branch"]),
  op("repoCreateBranch", "POST", "/repos/{owner}/{repo}/branches", ["repository"], ["owner", "repo"]),
  op("repoDeleteBranch", "DELETE", "/repos/{owner}/{repo}/branches/{branch}", ["repository"], ["owner", "repo", "branch"]),
  op("repoGetAllCommits", "GET", "/repos/{owner}/{repo}/commits", ["repository"], ["owner", "repo", "sha", "path", "stat", "verification", "files", "page", "limit"]),
  op("repoGetSingleCommit", "GET", "/repos/{owner}/{repo}/git/commits/{sha}", ["repository"], ["owner", "repo", "sha", "verification", "files"]),
  op("repoGetCommitPullRequest", "GET", "/repos/{owner}/{repo}/commits/{sha}/pull", ["repository"], ["owner", "repo", "sha"]),
  op("repoListTags", "GET", "/repos/{owner}/{repo}/tags", ["repository"], ["owner", "repo", "page", "limit"]),
  op("repoCreateTag", "POST", "/repos/{owner}/{repo}/tags", ["repository"], ["owner", "repo"]),
  op("repoGetTag", "GET", "/repos/{owner}/{repo}/tags/{tag}", ["repository"], ["owner", "repo", "tag"]),
  op("repoDeleteTag", "DELETE", "/repos/{owner}/{repo}/tags/{tag}", ["repository"], ["owner", "repo", "tag"]),
  op("repoListReleases", "GET", "/repos/{owner}/{repo}/releases", ["repository"], ["owner", "repo", "draft", "pre-release", "per_page", "page", "limit"]),
  op("repoCreateRelease", "POST", "/repos/{owner}/{repo}/releases", ["repository"], ["owner", "repo"]),
  op("repoGetRelease", "GET", "/repos/{owner}/{repo}/releases/{id}", ["repository"], ["owner", "repo", "id"]),
  op("repoEditRelease", "PATCH", "/repos/{owner}/{repo}/releases/{id}", ["repository"], ["owner", "repo", "id"]),
  op("repoDeleteRelease", "DELETE", "/repos/{owner}/{repo}/releases/{id}", ["repository"], ["owner", "repo", "id"]),
  op("repoGetLatestRelease", "GET", "/repos/{owner}/{repo}/releases/latest", ["repository"], ["owner", "repo"]),
  op("repoGetReleaseByTag", "GET", "/repos/{owner}/{repo}/releases/tags/{tag}", ["repository"], ["owner", "repo", "tag"]),
  op("repoListForks", "GET", "/repos/{owner}/{repo}/forks", ["repository"], ["owner", "repo", "page", "limit"]),
  op("repoCreateFork", "POST", "/repos/{owner}/{repo}/forks", ["repository"], ["owner", "repo"]),
  op("repoListHooks", "GET", "/repos/{owner}/{repo}/hooks", ["repository"], ["owner", "repo", "page", "limit"]),
  op("repoCreateHook", "POST", "/repos/{owner}/{repo}/hooks", ["repository"], ["owner", "repo"]),
  op("repoGetHook", "GET", "/repos/{owner}/{repo}/hooks/{id}", ["repository"], ["owner", "repo", "id"]),
  op("repoEditHook", "PATCH", "/repos/{owner}/{repo}/hooks/{id}", ["repository"], ["owner", "repo", "id"]),
  op("repoDeleteHook", "DELETE", "/repos/{owner}/{repo}/hooks/{id}", ["repository"], ["owner", "repo", "id"]),
  op("repoTestHook", "POST", "/repos/{owner}/{repo}/hooks/{id}/tests", ["repository"], ["owner", "repo", "id"]),
  op("repoListCollaborators", "GET", "/repos/{owner}/{repo}/collaborators", ["repository"], ["owner", "repo", "page", "limit"]),
  op("repoAddCollaborator", "PUT", "/repos/{owner}/{repo}/collaborators/{collaborator}", ["repository"], ["owner", "repo", "collaborator"]),
  op("repoDeleteCollaborator", "DELETE", "/repos/{owner}/{repo}/collaborators/{collaborator}", ["repository"], ["owner", "repo", "collaborator"]),
  op("repoCheckCollaborator", "GET", "/repos/{owner}/{repo}/collaborators/{collaborator}", ["repository"], ["owner", "repo", "collaborator"]),
  op("repoListTopics", "GET", "/repos/{owner}/{repo}/topics", ["repository"], ["owner", "repo", "page", "limit"]),
  op("repoUpdateTopics", "PUT", "/repos/{owner}/{repo}/topics", ["repository"], ["owner", "repo"]),
  op("repoGetGitRefs", "GET", "/repos/{owner}/{repo}/git/refs", ["repository"], ["owner", "repo"]),
  op("repoGetGitRefByType", "GET", "/repos/{owner}/{repo}/git/refs/{ref}", ["repository"], ["owner", "repo", "ref"]),
  op("repoGetRawFile", "GET", "/repos/{owner}/{repo}/raw/{filepath}", ["repository"], ["owner", "repo", "filepath", "ref", "token"]),
  op("repoGetArchive", "GET", "/repos/{owner}/{repo}/archive/{archive}", ["repository"], ["owner", "repo", "archive"]),
  op("repoListGitHooks", "GET", "/repos/{owner}/{repo}/hooks/git", ["repository"], ["owner", "repo"]),
  op("repoGetGitHook", "GET", "/repos/{owner}/{repo}/hooks/git/{id}", ["repository"], ["owner", "repo", "id"]),
  op("repoEditGitHook", "PATCH", "/repos/{owner}/{repo}/hooks/git/{id}", ["repository"], ["owner", "repo", "id"]),
  op("repoDeleteGitHook", "DELETE", "/repos/{owner}/{repo}/hooks/git/{id}", ["repository"], ["owner", "repo", "id"]),
  op("repoGetCombinedStatusByRef", "GET", "/repos/{owner}/{repo}/commits/{ref}/statuses", ["repository"], ["owner", "repo", "ref", "sort", "state", "page", "limit"]),
  op("repoListStatuses", "GET", "/repos/{owner}/{repo}/statuses/{sha}", ["repository"], ["owner", "repo", "sha", "sort", "state", "page", "limit"]),
  op("repoCreateStatus", "POST", "/repos/{owner}/{repo}/statuses/{sha}", ["repository"], ["owner", "repo", "sha"]),
  op("repoTransfer", "POST", "/repos/{owner}/{repo}/transfer", ["repository"], ["owner", "repo"]),
  op("repoGetByID", "GET", "/repositories/{id}", ["repository"], ["id"]),

  // ── Pull Requests ─────────────────────────────────────────────────────────────
  op("repoListPullRequests", "GET", "/repos/{owner}/{repo}/pulls", ["pull-request"], ["owner", "repo", "state", "sort", "milestone", "labels", "page", "limit"]),
  op("repoCreatePullRequest", "POST", "/repos/{owner}/{repo}/pulls", ["pull-request"], ["owner", "repo"]),
  op("repoGetPullRequest", "GET", "/repos/{owner}/{repo}/pulls/{index}", ["pull-request"], ["owner", "repo", "index"]),
  op("repoEditPullRequest", "PATCH", "/repos/{owner}/{repo}/pulls/{index}", ["pull-request"], ["owner", "repo", "index"]),
  op("repoMergePullRequest", "POST", "/repos/{owner}/{repo}/pulls/{index}/merge", ["pull-request"], ["owner", "repo", "index"]),
  op("repoIsPullRequestMerged", "GET", "/repos/{owner}/{repo}/pulls/{index}/merge", ["pull-request"], ["owner", "repo", "index"]),
  op("repoGetPullRequestCommits", "GET", "/repos/{owner}/{repo}/pulls/{index}/commits", ["pull-request"], ["owner", "repo", "index", "page", "limit"]),
  op("repoGetPullRequestFiles", "GET", "/repos/{owner}/{repo}/pulls/{index}/files", ["pull-request"], ["owner", "repo", "index", "page", "limit"]),
  op("repoListPullReviews", "GET", "/repos/{owner}/{repo}/pulls/{index}/reviews", ["pull-request"], ["owner", "repo", "index", "page", "limit"]),
  op("repoCreatePullReview", "POST", "/repos/{owner}/{repo}/pulls/{index}/reviews", ["pull-request"], ["owner", "repo", "index"]),
  op("repoGetPullReview", "GET", "/repos/{owner}/{repo}/pulls/{index}/reviews/{id}", ["pull-request"], ["owner", "repo", "index", "id"]),
  op("repoDeletePullReview", "DELETE", "/repos/{owner}/{repo}/pulls/{index}/reviews/{id}", ["pull-request"], ["owner", "repo", "index", "id"]),
  op("repoSubmitPullReview", "POST", "/repos/{owner}/{repo}/pulls/{index}/reviews/{id}", ["pull-request"], ["owner", "repo", "index", "id"]),
  op("repoGetPullReviewComments", "GET", "/repos/{owner}/{repo}/pulls/{index}/reviews/{id}/comments", ["pull-request"], ["owner", "repo", "index", "id"]),
  op("repoDismissPullReview", "POST", "/repos/{owner}/{repo}/pulls/{index}/reviews/{id}/dismissals", ["pull-request"], ["owner", "repo", "index", "id"]),
  op("repoUnDismissPullReview", "DELETE", "/repos/{owner}/{repo}/pulls/{index}/reviews/{id}/dismissals", ["pull-request"], ["owner", "repo", "index", "id"]),
  op("repoListPullRequestComments", "GET", "/repos/{owner}/{repo}/pulls/comments", ["pull-request"], ["owner", "repo", "page", "limit"]),
  op("repoUpdatePullRequest", "POST", "/repos/{owner}/{repo}/pulls/{index}/update", ["pull-request"], ["owner", "repo", "index", "style"]),

  // ── Users ─────────────────────────────────────────────────────────────────────
  op("userGetCurrent", "GET", "/user", ["user"], []),
  op("userGetSettings", "GET", "/user/settings", ["user"], []),
  op("userUpdateSettings", "PATCH", "/user/settings", ["user"], []),
  op("userGetByLogin", "GET", "/users/{username}", ["user"], ["username"]),
  op("userSearch", "GET", "/users/search", ["user"], ["q", "uid", "page", "limit"]),
  op("userListFollowers", "GET", "/users/{username}/followers", ["user"], ["username", "page", "limit"]),
  op("userListFollowing", "GET", "/users/{username}/following", ["user"], ["username", "page", "limit"]),
  op("userCheckFollowing", "GET", "/users/{username}/following/{target}", ["user"], ["username", "target"]),
  op("userCurrentCheckFollowing", "GET", "/user/following/{username}", ["user"], ["username"]),
  op("userFollow", "PUT", "/user/following/{username}", ["user"], ["username"]),
  op("userUnfollow", "DELETE", "/user/following/{username}", ["user"], ["username"]),
  op("userCurrentListRepos", "GET", "/user/repos", ["user"], ["page", "limit"]),
  op("userListStarred", "GET", "/users/{username}/starred", ["user"], ["username", "page", "limit"]),
  op("userCurrentListStarred", "GET", "/user/starred", ["user"], ["page", "limit"]),
  op("userCurrentStarRepo", "PUT", "/user/starred/{owner}/{repo}", ["user"], ["owner", "repo"]),
  op("userCurrentUnstarRepo", "DELETE", "/user/starred/{owner}/{repo}", ["user"], ["owner", "repo"]),
  op("userCurrentCheckStarring", "GET", "/user/starred/{owner}/{repo}", ["user"], ["owner", "repo"]),
  op("userListSubscriptions", "GET", "/users/{username}/subscriptions", ["user"], ["username", "page", "limit"]),
  op("userCurrentListSubscriptions", "GET", "/user/subscriptions", ["user"], ["page", "limit"]),
  op("userCreateToken", "POST", "/users/{username}/tokens", ["user"], ["username"]),
  op("userDeleteAccessToken", "DELETE", "/users/{username}/tokens/{token}", ["user"], ["username", "token"]),
  op("userListAccessTokens", "GET", "/users/{username}/tokens", ["user"], ["username", "page", "limit"]),
  op("userCurrentListGPGKeys", "GET", "/user/gpg_keys", ["user"], ["page", "limit"]),
  op("userCurrentGetGPGKey", "GET", "/user/gpg_keys/{id}", ["user"], ["id"]),
  op("userCurrentPostGPGKey", "POST", "/user/gpg_keys", ["user"], []),
  op("userCurrentDeleteGPGKey", "DELETE", "/user/gpg_keys/{id}", ["user"], ["id"]),
  op("userCurrentListKeys", "GET", "/user/keys", ["user"], ["fingerprint", "page", "limit"]),
  op("userCurrentGetKey", "GET", "/user/keys/{id}", ["user"], ["id"]),
  op("userCurrentPostKey", "POST", "/user/keys", ["user"], []),
  op("userCurrentDeleteKey", "DELETE", "/user/keys/{id}", ["user"], ["id"]),
  op("userListEmails", "GET", "/user/emails", ["user"], []),
  op("userAddEmail", "POST", "/user/emails", ["user"], []),
  op("userDeleteEmail", "DELETE", "/user/emails", ["user"], []),
  op("userCurrentListOrgs", "GET", "/user/orgs", ["user"], ["page", "limit"]),
  op("userListTeams", "GET", "/user/teams", ["user"], ["page", "limit"]),

  // ── Organizations ─────────────────────────────────────────────────────────────
  op("orgGet", "GET", "/orgs/{org}", ["organization"], ["org"]),
  op("orgCreate", "POST", "/orgs", ["organization"], []),
  op("orgEdit", "PATCH", "/orgs/{org}", ["organization"], ["org"]),
  op("orgDelete", "DELETE", "/orgs/{org}", ["organization"], ["org"]),
  op("orgListMembers", "GET", "/orgs/{org}/members", ["organization"], ["org", "limit", "page"]),
  op("orgIsMember", "GET", "/orgs/{org}/members/{username}", ["organization"], ["org", "username"]),
  op("orgDeleteMember", "DELETE", "/orgs/{org}/members/{username}", ["organization"], ["org", "username"]),
  op("orgListPublicMembers", "GET", "/orgs/{org}/public_members", ["organization"], ["org", "page", "limit"]),
  op("orgIsPublicMember", "GET", "/orgs/{org}/public_members/{username}", ["organization"], ["org", "username"]),
  op("orgConcealMember", "DELETE", "/orgs/{org}/public_members/{username}", ["organization"], ["org", "username"]),
  op("orgPublicizeMember", "PUT", "/orgs/{org}/public_members/{username}", ["organization"], ["org", "username"]),
  op("orgListRepos", "GET", "/orgs/{org}/repos", ["organization"], ["org", "page", "limit"]),
  op("orgListTeams", "GET", "/orgs/{org}/teams", ["organization"], ["org", "page", "limit"]),
  op("orgCreateTeam", "POST", "/orgs/{org}/teams", ["organization"], ["org"]),
  op("orgGetTeam", "GET", "/teams/{id}", ["organization"], ["id"]),
  op("orgEditTeam", "PATCH", "/teams/{id}", ["organization"], ["id"]),
  op("orgDeleteTeam", "DELETE", "/teams/{id}", ["organization"], ["id"]),
  op("orgListTeamMembers", "GET", "/teams/{id}/members", ["organization"], ["id", "page", "limit"]),
  op("orgListTeamRepos", "GET", "/teams/{id}/repos", ["organization"], ["id", "page", "limit"]),
  op("orgAddTeamMember", "PUT", "/teams/{id}/members/{username}", ["organization"], ["id", "username"]),
  op("orgRemoveTeamMember", "DELETE", "/teams/{id}/members/{username}", ["organization"], ["id", "username"]),
  op("orgAddTeamRepository", "PUT", "/teams/{id}/repos/{org}/{repo}", ["organization"], ["id", "org", "repo"]),
  op("orgRemoveTeamRepository", "DELETE", "/teams/{id}/repos/{org}/{repo}", ["organization"], ["id", "org", "repo"]),
  op("orgListHooks", "GET", "/orgs/{org}/hooks", ["organization"], ["org", "page", "limit"]),
  op("orgCreateHook", "POST", "/orgs/{org}/hooks", ["organization"], ["org"]),
  op("orgGetHook", "GET", "/orgs/{org}/hooks/{id}", ["organization"], ["org", "id"]),
  op("orgEditHook", "PATCH", "/orgs/{org}/hooks/{id}", ["organization"], ["org", "id"]),
  op("orgDeleteHook", "DELETE", "/orgs/{org}/hooks/{id}", ["organization"], ["org", "id"]),
  op("orgListUserOrgs", "GET", "/users/{username}/orgs", ["organization"], ["username", "page", "limit"]),
  op("teamSearch", "GET", "/orgs/{org}/teams/search", ["organization"], ["org", "q", "include_desc", "page", "limit"]),

  // ── Notifications ─────────────────────────────────────────────────────────────
  op("notifyGetList", "GET", "/notifications", ["notification"], ["all", "status-types", "subject-type", "since", "before", "page", "limit"]),
  op("notifyReadList", "PUT", "/notifications", ["notification"], ["all", "status-types", "to-status", "last_read_at"]),
  op("notifyGetThread", "GET", "/notifications/threads/{id}", ["notification"], ["id"]),
  op("notifyReadThread", "PATCH", "/notifications/threads/{id}", ["notification"], ["id", "to-status"]),
  op("notifyGetRepoList", "GET", "/repos/{owner}/{repo}/notifications", ["notification"], ["owner", "repo", "all", "status-types", "subject-type", "since", "before", "page", "limit"]),
  op("notifyReadRepoList", "PUT", "/repos/{owner}/{repo}/notifications", ["notification"], ["owner", "repo", "all", "status-types", "to-status", "last_read_at"]),
  op("notifyNewAvailable", "GET", "/notifications/new", ["notification"], []),

  // ── Settings / Misc ───────────────────────────────────────────────────────────
  op("getVersion", "GET", "/version", ["settings"], []),
  op("getNodeInfo", "GET", "/nodeinfo", ["settings"], []),
  op("getSigningKey", "GET", "/signing-key.gpg", ["settings"], []),
];

OPERATIONS.sort((a, b) => a.operationId.localeCompare(b.operationId));

export function loadGiteaOperations(): GiteaRestOperation[] {
  return OPERATIONS;
}
